### ISSUE TITLE
Still doesn't build with kwin 5.19+

### ISSUE THREAD

**Issue by felixonmars** [linuxdeepin/dde-kwin#127]
After https://github.com/linuxdeepin/dde-kwin/commit/7bb00d244b95b0e2193556d5ff9e73dd29a54d4a, dde-kwin still doesn't build with kwin 5.19:

```
plugins/kwineffects/blur/blur.cpp: In constructor ‘BlurEffect::BlurEffect(QObject*, const QVariantList&)’:
plugins/kwineffects/blur/blur.cpp:65:28: error: ‘class KWaylandServer::BlurManagerInterface’ has no member named ‘create’
   65 |             m_blurManager->create();
      |                            ^~~~~~
```

I removed this line in my previous patch. Not sure what is the right fix, though.
